apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chaos-monkey
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chaos-monkey
    spec:
      containers:
        - name: chaos-monkey
          image: ocadotechnology/kubernetes-chaosmonkey:latest
          resources:
            requests:
              memory: "32Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.1"
          env:
            - name: "CHAOS_MONKEY_KILL_FREQUENCY_SECONDS"
              value: "3600"
