apiVersion: v1
kind: ReplicationController
metadata:
  name: chaos-monkey
spec:
  replicas: 1
  selector:
    app: chaos-monkey
  template:
    metadata:
      name: chaos-monkey
      labels:
        app: chaos-monkey
    spec:
      containers:
        - name: chaos-monkey
          image: dk.tech.cit.lastmile.com/fabric8/chaos-monkey:2.2.115
          ports:
            - containerPort: 8778
          resources:
            requests:
              memory: "256Mi"
              cpu: "1"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: KUBERNETES_MASTER
              value: "https://kubernetes"
            - name: KUBERNETES_NAMESPACE
              value: "default"
            - name: "CHAOS_MONKEY_INCLUDES"
              value: "*"
            - name: "CHAOS_MONKEY_KILL_FREQUENCY_SECONDS"
              value: "30"
